springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true

spring:
  application:
    name: user-service

  web:
    locale-resolver: fixed
    locale: pt_BR

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    ddl-auto: none

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mq:
  queues:
    notify: notify

jwt:
  secret: umaChaveMuitoSeguraDePeloMenos32Caracteres!

logging:
  level:
    io.github.modenadev.userproject.repositories.ViaCepClient: DEBUG

